import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, collection, query, where, orderBy, onSnapshot, addDoc, updateDoc, deleteDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
const config={apiKey:"AIzaSyDYE1h4hmU8ppSa18Jz-veC6GADBgsIa3g",authDomain:"tee-shirt-2.firebaseapp.com",projectId:"tee-shirt-2",storageBucket:"tee-shirt-2.firebasestorage.app",messagingSenderId:"795409975965",appId:"1:795409975965:web:679a7672811d748677e274"};
const app=getApps()[0]||initializeApp(config),db=getFirestore(app),auth=getAuth(app),$=id=>document.getElementById(id);let all=[],admin=false;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(a,manage=false){const d=a.publishedAt?.toDate?.()||a.scheduledAt?.toDate?.()||new Date();return `<article class="announcement-card" data-priority="${esc(a.priority)}"><h3>${a.pinned?'📌 ':''}${esc(a.title)}</h3><div class="announcement-meta"><span class="priority-label">${esc(a.priority||'Normal')}</span><span>${d.toLocaleDateString()}</span><span>By ${esc(a.author||'Admin')}</span>${manage?`<span>${esc(a.status)}</span>`:''}</div><p>${esc(a.message)}</p>${manage?`<div class="announcement-actions"><button data-edit="${a.id}" class="secondary-btn">Edit</button><button data-archive="${a.id}" class="ghost-btn">Archive</button><button data-delete="${a.id}" class="danger-btn">Delete</button></div>`:''}</article>`}
function render(){const pub=all.filter(a=>a.status==='published').sort((a,b)=>(b.pinned-a.pinned)||((b.publishedAt?.seconds||0)-(a.publishedAt?.seconds||0)));$('announcementList').innerHTML=(pub.slice(0,3).map(a=>card(a)).join('')||'<p class="helper-text">No announcements yet.</p>');$('adminAnnouncementList').innerHTML=admin?all.map(a=>card(a,true)).join(''):''}
onSnapshot(query(collection(db,'announcements'),orderBy('createdAt','desc')),s=>{all=s.docs.map(d=>({id:d.id,...d.data()}));render()},()=>{$('announcementList').innerHTML='<p class="helper-text">Announcements are unavailable until Firebase rules are deployed.</p>'});
$('viewAllAnnouncements').onclick=()=>{$('announcementList').innerHTML=all.filter(a=>a.status==='published').map(a=>card(a)).join('')};
$('announcementSubscribeForm').onsubmit=async e=>{e.preventDefault();const email=$('announcementEmail').value.trim().toLowerCase();try{await addDoc(collection(db,'announcementSubscriptions'),{email,status:'pending',createdAt:serverTimestamp(),source:'website'});$('subscriptionMessage').textContent='Check your email to confirm your subscription.';e.target.reset()}catch{$('subscriptionMessage').textContent='Subscription could not be saved. Please try again.'}};
$('announcementLogin').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('adminEmail').value,$('adminPassword').value)}catch{$('subscriptionMessage').textContent='Admin sign-in failed.'}};$('announcementSignOut').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{admin=!!u&&!!(await u.getIdTokenResult()).claims.admin;$('announcementLogin').hidden=admin;$('announcementEditor').hidden=!admin;$('announcementSignOut').hidden=!admin;render()});
$('previewAnnouncement').onclick=()=>{$('announcementPreview').hidden=false;$('announcementPreview').innerHTML=card({title:$('announcementTitleInput').value,message:$('announcementMessage').value,author:$('announcementAuthor').value,priority:$('announcementPriority').value,pinned:$('announcementPinned').checked,status:'preview'})};
$('announcementEditor').onsubmit=async e=>{e.preventDefault();if(!admin)return;const action=e.submitter?.dataset.action||'draft',schedule=$('announcementSchedule').value;const data={title:$('announcementTitleInput').value.trim(),message:$('announcementMessage').value.trim(),author:$('announcementAuthor').value.trim(),priority:$('announcementPriority').value,pinned:$('announcementPinned').checked,notifyOnPublish:$('announcementNotify').checked,status:action==='draft'?'draft':schedule?'scheduled':'published',scheduledAt:schedule?new Date(schedule):null,updatedAt:serverTimestamp()};if(data.status==='published')data.publishedAt=serverTimestamp();const id=$('announcementId').value;if(id)await updateDoc(doc(db,'announcements',id),data);else await addDoc(collection(db,'announcements'),{...data,createdAt:serverTimestamp(),notificationState:'pending'});e.target.reset();$('announcementId').value=''};
$('adminAnnouncementList').onclick=async e=>{const id=e.target.dataset.edit||e.target.dataset.archive||e.target.dataset.delete;if(!id||!admin)return;const a=all.find(x=>x.id===id);if(e.target.dataset.edit){$('announcementId').value=id;$('announcementTitleInput').value=a.title;$('announcementMessage').value=a.message;$('announcementAuthor').value=a.author;$('announcementPriority').value=a.priority;$('announcementPinned').checked=!!a.pinned}else if(e.target.dataset.archive)await updateDoc(doc(db,'announcements',id),{status:'archived',updatedAt:serverTimestamp()});else if(confirm('Delete this announcement permanently?'))await deleteDoc(doc(db,'announcements',id))};
